### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for

### ISSUE THREAD

**Issue by dench1k** [joshunrau/ytdl-mp3#58]
Hey, Josh. I've updated the package for the recent version and now for every download attempt an error. Here's my stacktrace:
`λ ytdl-mp3 https://www.youtube.com/watch?v=ZAjKsE5MNeU
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for C:\Users\admin\AppData\Roaming\npm\node_modules\ytdl-mp3\bin\ytdl-mp3. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file C:\Users\admin\AppData\Roaming\npm\node_modules\ytdl-mp3\package.json caused this "type":"module" context. Try changing C:\Users\admin\AppData\Roaming\npm\node_modules\ytdl-mp3\bin\ytdl-mp3 to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"ytdl-mp3":".\bin\ytdl-mp3.js"}}
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:431:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at #createModuleJob (node:internal/modules/esm/loader:369:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'`

Node.js v18.0.0

**Comment by dench1k** [comment]
Not sure if that's it, but probably would be useful 
https://stackoverflow.com/questions/63445821/ts-node-execute-typescript-with-module-import-and-module-defined

**Comment by joshunrau** [comment]
Thanks for the report. I will investigate tmr.

**Comment by joshunrau** [comment]
Hi sorry for the delay. Have been very busy lately. This should be fixed in the latest version :)

**Comment by dench1k** [comment]
Hi! Thanks for the feedback and your time. I will check the latest version in the evening :)

**Comment by dench1k** [comment]
λ ytdl-mp3 https://www.youtube.com/watch?v=te6EdjqdzPA
ERROR: Failed to fetch info for video with URL: https://www.youtube.com/watch?v=te6EdjqdzPA

**Comment by dench1k** [comment]
This is my log after update :(

**Comment by dench1k** [comment]
Actually there's no npm after my update and I can't do anything related to npm. Everytime this error:

 npm list -g npm
evalmachine.<anonymous>:43
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:43:5
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0

Probably I typed something wrong, dunno.

**Comment by joshunrau** [comment]
@dench1k try downgrading to node v20.51. At my work, we are having lots of problems with v20.6 due to some changes related to env variables. Could be it

**Comment by dench1k** [comment]
The error above was due to some npm crush on my system after trying to revert npm version. As a result, I couldn't do any command with npm (even to check current version). Spent the whole Friday's evening to fix the issue and the only solution was:
- to completely delete the npm folder in `%AppData%\npm\`
- download the latest `https://github.com/npm/cli/releases/latest`
- paste this to `%AppData%\npm\`
- run `npm i -g npm`

That's how I've got the latest npm and node version together, so at least it works in the system. Today I started to test this setup with the lastest package vesion of ytdl-mp3 and result was the same: 
` ytdl-mp3 https://youtu.be/Y9yHZ-Gwdk8?si=EUy9ULhB6Jr-FAWU
ERROR: Failed to fetch info for video with URL: https://youtu.be/Y9yHZ-Gwdk8?si=EUy9ULhB6Jr-FAWU`

Tried to revert to  `ytdl-mp3@3.1.1` and  `ytdl-mp3@3.1.0` versions, but got errors "old" errors too (which is quite obvious I guess). The only current soluton was reverting to `ytdl-mp3@3.0.0` of the package, sadly. The only thing I haven't tested is reverting to the prev. version on node (which you suggested - `node v20.51`), because at home I don't have nvm on a windows machine. Hope this feedback will be helpful and thank you for your time, Joshua

**Comment by joshunrau** [comment]
Hey,

So, I added a verbose option a little while back. You can use it like this:

```shell
❯ ytdl-mp3 --verbose "https://www.youtube.com/watch\?v\=Y9yHZ-Gwdk8"
Error: No video id found: "https://www.youtube.com/watch\?v\=Y9yHZ-Gwdk8"
    at exports.getURLVideoID (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/node_modules/ytdl-core/lib/url-utils.js:36:11)
    at exports.getVideoID (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/node_modules/ytdl-core/lib/url-utils.js:61:20)
    at exports.<computed> [as getInfo] (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/node_modules/ytdl-core/lib/info.js:484:29)
    at _Downloader.<anonymous> (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/dist/index.cjs:210:56)
    at Generator.next (<anonymous>)
    at /Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/dist/index.cjs:46:61
    at new Promise (<anonymous>)
    at __async (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/dist/index.cjs:30:10)
    at _Downloader.downloadSong (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/dist/index.cjs:206:12)
    at main (/Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/bin/ytdl-mp3.cjs:23:22)
YtdlMp3Error: Failed to fetch info for video with URL: https://www.youtube.com/watch\?v\=Y9yHZ-Gwdk8
    at /Users/joshua/.nvm/versions/node/v20.5.1/lib/node_modules/ytdl-mp3/dist/index.cjs:211:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: Failed to fetch info for video with URL: https://www.youtube.com/watch\?v\=Y9yHZ-Gwdk8
```

As you can see, the problem is `Error: No video id found: "https://www.youtube.com/watch\?v\=Y9yHZ-Gwdk8"`. Right now I am swamped and don't have time to figure this out atm since it seems to only be a problem with this video. However, if you want to look into the `ytdl-core` docs and implement a PR to fix it would be greatly appreciated!

**Comment by joshunrau** [comment]
I updated the deps so that the message is gone now. Try installing the latest version again and lmk if it works.

Tested version:
```
npm install -g ytdl-mp3@5.2.2
```

**Comment by dench1k** [comment]
I've just updated to the last version and tested - everything works like a charm. Thanks, Joshua!

**Comment by dench1k** [comment]
Tried to download some videos today and havin' this error

```
ytdl-mp3 https://www.youtube.com/watch?v=IkSG908JpF8
WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse decipher function.
Stream URLs will be missing.
Please report this issue by uploading the "1745345192498-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.
WARNING: Could not parse n transform function.
Please report this issue by uploading the "1745345192511-base.js" file on https://github.com/distubejs/ytdl-core/issues/144.
ERROR: Failed to download video
```

I understand, that the issue is because of dependencies, but maybe it's gonna be useful info
